#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep  6 09:40:59 2022

@author: e.akkouche
"""

import numpy as np
import matplotlib.pyplot as plt

# from Objfun import compute_symmpad_per_band
from astropy.io import fits
from CONSTANTS import *

import warnings
warnings.filterwarnings('ignore')

path = '/media/e.akkouche/DONNEES/Fusion_data/L_curve_data/'

mus = 10**np.linspace(3,5,10)

Regul = []
Residu = []

for k in range (len(mus)):
    
    Regul.append(np.load(path+'regul_mu_'+str(k+1)+'.npy'))
    Residu.append(np.load(path+'residu_mu_'+str(k+1)+'.npy'))


plt.plot(np.abs(Regul),np.abs(Residu))

reg = np.abs(Regul)

res = np.abs(np.abs(Residu))